version: "3.9"
services:
  php-app:
    image: php:8.2-apache
    container_name: php-service
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    environment:
      command: bash -c "composer install && apache2-foreground"
    restart: always

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app